drop database dbpesquisaolimpiadas;
create database dbpesquisaOlimpiadas;
use dbpesquisaOlimpiadas;


-- TABELAS SEM CHAVES ESTRANGEIRAS
CREATE TABLE edicao (
  codedicao int(11) NOT NULL primary key auto_increment,
  ano int(11) NOT NULL,
  sede varchar(30) NOT NULL
);


CREATE TABLE estados (
  codEstado int(11) NOT NULL primary key auto_increment,
  nomeEstado varchar(255) NOT NULL
);


CREATE TABLE modalidades (
  codModalidade int(11) NOT NULL primary key auto_increment,
  nomeModalidade varchar(255) NOT NULL
);


-- TABELAS COM AS CHAVES ESTRANGEIRAS

CREATE TABLE cidades (
  codCidade int(11) NOT NULL primary key auto_increment,
  nomeCidade varchar(255) NOT NULL,
  codEstado int(11) DEFAULT NULL,
  foreign key (codEStado) references estados (codEstado) 
); 


CREATE TABLE atletas (
  codAtleta int(11) NOT NULL primary key auto_increment,
  nomeAtleta varchar(255) NOT NULL,
  dataNascimento varchar(20) NOT NULL,
  sexo char(1) DEFAULT NULL,
  altura decimal(5,2) DEFAULT NULL,
  peso decimal(5,2) DEFAULT NULL,
  codCidade int(11) DEFAULT NULL,
  codModalidade int(11) DEFAULT NULL,
  foreign key (codCidade) references cidades(codCidade),
  foreign key (codModalidade) references modalidades(codModalidade)
);



CREATE TABLE provas (
  codProva int(11) NOT NULL primary key auto_increment,
  nomeProva varchar(255) NOT NULL,
 codModalidade int(11) DEFAULT NULL,
  foreign key (codModalidade) references modalidades (codModalidade)
);


CREATE TABLE resultadosatletas (
  codAtletaRes int(11) NOT NULL primary key auto_increment,
  resultado varchar(255) DEFAULT NULL,
  medalha varchar(255) DEFAULT NULL,
  codEdicao int(11) DEFAULT NULL,
  codAtleta int(11) DEFAULT NULL,
  codProva int(11) DEFAULT NULL,
  foreign key (codAtleta) references atletas(codAtleta),
  foreign key (codProva) references provas(codProva),
  foreign key (codEdicao) references edicao (codedicao)

);


INSERT INTO `estados` (`codEstado`, `nomeEstado`) VALUES
(1, 'Acre'),
(2, 'Alagoas'),
(3, 'Alemanha'),
(4, 'Amapá'),
(5, 'Amazonas'),
(6, 'Argentina'),
(7, 'Armênia'),
(8, 'Austrália'),
(9, 'Bahia'),
(10, 'Bielorussia'),
(11, 'Bélgica'),
(12, 'Ceará'),
(13, 'China'),
(14, 'Colômbia'),
(15, 'Croácia'),
(16, 'Cuba'),
(17, 'Distrito Federal'),
(18, 'EUA'),
(19, 'Espanha'),
(20, 'Espírito Santo'),
(21, 'França'),
(22, 'Goiás'),
(23, 'Grã-Bretanha'),
(24, 'Holanda'),
(25, 'Hungria'),
(26, 'Inglaterra'),
(27, 'Itália'),
(28, 'Japão'),
(29, 'Lituânia'),
(30, 'Maranhão'),
(31, 'Mato Grosso'),
(32, 'Mato Grosso do Sul'),
(33, 'Minas Gerais'),
(34, 'Paraná'),
(35, 'Paraíba'),
(36, 'Pará'),
(37, 'Pernambuco'),
(38, 'Piauí'),
(39, 'Polônia'),
(40, 'Portugal'),
(41, 'Rio Grande do Norte'),
(42, 'Rio Grande do Sul'),
(43, 'Rio de Janeiro'),
(44, 'Rondônia'),
(45, 'Roraima'),
(46, 'Santa Catarina'),
(47, 'Sergipe'),
(48, 'Suiça'),
(49, 'Suécia'),
(50, 'São Paulo'),
(51, 'Sérvia'),
(52, 'Uruguai'),
(53, 'nan');

insert into cidades (nomeCidade,codEstado) values

('?', 50),
('Adamantina', 50),
('Aguaí', 50),
('Americana', 50),
('Amparo', 50),
('Andradina', 50),
('Araraquara', 50),
('Araras', 50),
('Araçatuba', 50),
('Artur Nogueira', 50),
('Arujá', 50),
('Atibaia', 50),
('BASTOS', 50),
('Barra Bonita', 50),
('Barueri', 50),
('Bauru', 50),
('Boa Esperança do Sul', 50),
('Botucatu', 50),
('Brasília', 50),
('CAMPINAS', 50),
('Caieiras', 50),
('Campinas', 50),
('Campo Limpo Paulista', 50),
('Campos do Jordão', 50),
('Capivari', 50),
('Capão Bonito', 50),
('Caraguatatuba', 50),
('Carapicuíba', 50),
('Casa Branca', 50),
('Catanduva', 50),
('Colina', 50),
('Conchal', 50),
('Coronel Macedo', 50),
('Cosmopólis', 50),
('Cotia', 50),
('Cruzeiro', 50),
('Cubatão', 50),
('Descalvado', 50),
('Diadema', 50),
('Dracena', 50),
('Ferraz de Vasconcelos', 50),
('Franca', 50),
('Garça', 50),
('Guararapes', 50),
('Guaratinguetá', 50),
('Guarujá', 50),
('Guarulhos', 50),
('Guaíra', 50),
('ITARIRI', 50),
('ITU', 50),
('Ibirá', 50),
('Ibitinga', 50),
('Iguape', 50),
('Ilha Solteira', 50),
('Ilhabela', 50),
('Indiaporã', 50),
('Ipaussu', 50),
('Itanhaém', 50),
('Itapeva', 50),
('Itatiba', 50),
('Itu', 50),
('Ituverava', 50),
('Jacareí', 50),
('Jandira', 50),
('Jaú', 50),
('Jundiaí', 50),
('Juquiá', 50),
('Leme', 50),
('Lençóis Paulista', 50),
('Limeira', 50),
('Lins', 50),
('Lorena', 50),
('Lucélia', 50),
('Marília', 50),
('Matão', 50),
('Mauá', 50),
('Mococa', 50),
('Mogi das Cruzes', 50),
('Morungaba', 50),
('Nova Odessa', 50),
('Orlândia', 50),
('Osasco', 50),
('Osvaldo Cruz', 50),
('Pacaembu', 50),
('Paraguaçu Paulista', 50),
('Parapuã', 50),
('Pariquera-Açu', 50),
('Patrocinio Paulista', 50),
('Pedregulho', 50),
('Pedro de Toledo', 50),
('Penápolis', 50),
('Peruíbe', 50),
('Pindamonhangaba', 50),
('Piracicaba', 50),
('Piraju', 50),
('Pirassununga', 50),
('Porto Ferreira', 50),
('Potirendaba', 50),
('Praia Grande', 50),
('Presidente Prudente', 50),
('Promissão', 50),
('Quintana', 50),
('Registro', 50),
('Ribeirão Preto', 50),
('Rio Claro', 50),
('Rio de Janeiro', 50),
('Rosárial', 50),
('Rubineia', 50),
('Salto', 50),
('Santa Bárbara d Oeste', 50),
('Santa Maria da Serra', 50),
('Santa Rita do Passa Quatro', 50),
('Santo André', 50),
('Santo Antônio de Posse', 50),
('Santos', 50),
('Saudades', 50),
('Sertãozinho', 50),
('Sorocaba', 50),
('Sumaré', 50),
('Suzano', 50),
('São Bernardo do Campo', 50),
('São Caetano do Sul', 50),
('São Carlos', 50),
('São Joaquim da Barra', 50),
('São José do Rio Preto', 50),
('São José dos Campos', 50),
('São João da Boa Vista', 50),
('São Manuel', 50),
('São Paulo', 50),
('São Roque', 50),
('São Sebastião', 50),
('São Vicente', 50),
('Taubaté', 50),
('Tietê', 50),
('Tupi Paulista', 50),
('Tupã', 50),
('Ubatuba', 50),
('Valinhos', 50),
('Vinhedo', 50),
('Vista Alegre do Alto', 50),
('Votorantim', 50),
('Álvares Machado', 50);

insert into  modalidades (nomeModalidade) values
('Ginástica Artística');

insert into provas (nomeProva,codModalidade) values
('Argolas Masculino',1),
('Barra Fixa',1),  
('Barra Fixa Masculino',1),  
('Barras Assimétricas Feminino',1),  
('Barras Paralelas Masculino',1),  
('Cavalo com Alças Masculino', 1),  
('Equipes Feminino',1),  
('Equipes Masculino',1),  
('Individual All-Around Feminino',1),  
('Individual All-Around Masculino',1),  
('Individual Geral Feminino',1),  
('Individual Geral Masculino',1),  
('Salto sobre a mesa Feminino',1),  
('Salto sobre a mesa Masculino',1),  
('Solo Feminino',1),  
('Solo Masculino',1),  
('Trave de Equilibrio Feminino',1);

insert into atletas(nomeAtleta,dataNascimento,sexo,altura,peso,codCidade,codModalidade)
  values ('Rebeca Rodrigues de Andrade', '1999-05-08', 'F','1.51','46', 2 ,1 );
INSERT INTO modalidades (nomeModalidade) VALUES
('Atletismo'),('Natação'),('Vôlei de Quadra'),('Vôlei de Praia');
INSERT INTO provas (nomeProva, codModalidade) VALUES
('10000m Feminino', 3),
('10000m Masculino', 3),
('100m Feminino', 3),
('100m Masculino', 3),
('100m com barreiras Feminino', 3),
('110m com Barreiras Masculino', 3),
('1500m Masculino', 3),
('200m Feminino', 3),
('200m Masculino', 3),
('20km Marcha Atlética Feminina', 3),
('20km Marcha Atlética Masculino', 3),
('3000m com Obstáculos Feminino', 3),
('3000m com Obstáculos Masculino', 3),
('400m Feminino', 3),
('400m Feminino Feminino', 3),
('400m Masculino', 3),
('400m com Barreiras Feminina', 3),
('400m com Barreiras Feminino', 3),
('400m com Barreiras Masculino', 3),
('5000m Feminino', 3),
('5000m Masculino', 3),
('50km Marcha Atlética', 3),
('60m Masculino', 3),
('800m Feminino', 3),
('800m Masculino', 3),
('80m com Barreiras Feminino', 3),
('Arremesso de Peso Feminino', 3),
('Arremesso de Peso Masculino', 3),
('Arremesso do Peso Masculino', 3),
('Cross Country Masculino', 3),
('Decatlon', 3),
('Decatlon Masculino', 3),
('Heptatlo Feminino', 3),
('Lançamento de Dardo Feminino', 3),
('Lançamento de Dardo Masculino', 3),
('Lançamento de Disco Feminino', 3),
('Lançamento de Disco Masculino', 3),
('Lançamento do Dardo', 3),
('Lançamento do Dardo Feminino', 3),
('Lançamento do Disco Feminino', 3),
('Lançamento do Disco Masculino', 3),
('Lançamento do Martelo Masculino', 3),
('Maratona Feminina', 3),
('Maratona Masculina', 3),
('Marcha Atletica Masculina 20km', 3),
('Marcha Atlética 20 Km Feminino', 3),
('Marcha Atlética 20 Km Masculino', 3),
('Marcha Atlética 50 Km Masculino', 3),
('Marcha Atlética Feminino 20km', 3),
('Pentatlo Feminino', 3),
('Revezamento 4 x 100m Feminino', 3),
('Revezamento 4 x 100m Masculino', 3),
('Revezamento 4 x 400 Masculino', 3),
('Revezamento 4 x 400m Feminino', 3),
('Revezamento 4 x 400m Masculino', 3),
('Revezamento 4 x 400m Misto', 3),
('Revezamento Marcha Atlética Misto', 3),
('Revezametno 4 x 400m Masculino', 3),
('Salto Triplo Feminino', 3),
('Salto Triplo Masculino', 3),
('Salto com Vara Feminino', 3),
('Salto com Vara Masculino', 3),
('Salto em Altura Feminino', 3),
('Salto em Altura Masculino', 3),
('Salto em Distância Feminino', 3),
('Salto em Distância Masculino', 3)

INSERT INTO provas (nomeProva, codModalidade) VALUES
('100m Borboleta Feminino', 4),
('100m Borboleta Masculino', 4),
('100m Costas Feminino', 4),
('100m Costas Masculino', 4),
('100m Livre Feminino', 4),
('100m Livre Masculino', 4),
('100m Nado Livre Masculino', 4),
('100m Peito Feminino', 4),
('100m Peito Masculino', 4),
('1500m Livre Feminino', 4),
('1500m Livre Masculino', 4),
('1500m Nado Livre', 4),
('200m Borboleta Feminino', 4),
('200m Borboleta Masculino', 4),
('200m Costas Masculino', 4),
('200m Livre Feminino', 4),
('200m Livre Masculino', 4),
('200m Medley Feminino', 4),
('200m Medley Masculino', 4),
('200m Nado Livre', 4),
('200m Nado Livre Masculino', 4),
('200m Peito Feminino', 4),
('200m Peito Masculino', 4),
('400m Livre Feminino', 4),
('400m Livre Masculino', 4),
('400m Medley Feminino', 4),
('400m Medley Masculino', 4),
('400m Nado Livre Feminino', 4),
('400m Nado Livre Masculino', 4),
('50m Livre Feminino', 4),
('50m Livre Masculino', 4),
('800m Livre Feminino', 4),
('800m Livre Masculino', 4),
('800m Nado Livre Feminino', 4),
('800m Nado Livre Natação', 4),
('Mixed 4 x 100m Medley Relay', 4),
('Revezamento 4 x 100m Nado Livre Masculino', 4),
('Revezamento 4 x 200m Nado Livre Masculino', 4),
('Revezamento 4x100m Livre Feminino', 4),
('Revezamento 4x100m Livre Masculino', 4),
('Revezamento 4x100m Medley Feminino', 4),
('Revezamento 4x100m Medley Masculino', 4),
('Revezamento 4x100m Medley Misto', 4),
('Revezamento 4x100m Nado Livre Feminino', 4),
('Revezamento 4x200m Livre Feminino', 4),
('Revezamento 4x200m Livre Masculino', 4),
('Revezamento 4x200m Nado Livre Feminino', 4);

INSERT INTO `atletas` (`nomeAtleta`, `dataNascimento`, `sexo`, `altura`, `peso`, `codCidade`, `codModalidade`) VALUES
('Adhemar Ferreira da Silva', '1927-09-29', 'M', NULL, NULL, 129, 3),
('Aderval Luiz Arvani', '1949-01-07', 'M', NULL, NULL, 129, 5),
('Stephanie Balduccini', '2004-09-20', 'F',NULL, NULL, 129, 4),
('Thaissa Barbosa Presti', '1988-04-26', 'F',NULL, NULL, 129, 3),
('Wanda dos Santos', '1932-06-01', 'F', NULL, NULL, 129, 3),
('Manuel dos Santos Filho', '1939-02-22', 'M', NULL, NULL,129, 4),
('Marcelo Teles Negrão', '1972-10-10', 'M', NULL, NULL, 129, 5),
('Fofão', '1970-03-10', 'F', NULL, NULL, 129, 5);

INSERT INTO `resultadosatletas` (codAtleta, codProva,  codedicao, resultado, medalha) VALUES
(10, 131, 18, '3º Lugar', 'Bronze'),
(10, 131, 19, '3º Lugar', 'Bronze'),
(10, 131, 20, '4º Lugar', '0'),
(10, 131, 21, '1º Lugar', 'Ouro'),
(4, 78, 7, '1º Lugar', 'Ouro'),
(4, 78, 8, '1º Lugar', 'Ouro'),
(6, 69, 21, '3º Lugar', 'Bronze');